/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import model.BudgetSight;
import model.VoceBudget;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author dario
 */
public class Eliminazione extends javax.swing.JFrame {
    private BudgetSight bs;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Eliminazione.class.getName());

    /**
     * Creates new form Eliminazione
     */
    public Eliminazione(BudgetSight bs) {

        initComponents();

        this.bs = bs;

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Output = new javax.swing.JLabel();
        EliminaB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(188, 210, 243));

        Output.setBackground(new java.awt.Color(0, 0, 0));
        Output.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Output.setText("Eliminazione");

        EliminaB.setBackground(new java.awt.Color(51, 51, 255));
        EliminaB.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        EliminaB.setForeground(new java.awt.Color(255, 255, 255));
        EliminaB.setText("Clicca quì per Eliminare uno o più elementi");
        EliminaB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminaBMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Output)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(EliminaB, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Output)
                .addGap(29, 29, 29)
                .addComponent(EliminaB)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminaBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminaBMouseClicked
                // Controlla che ci siano dati
        if (bs == null || bs.getElenco().isEmpty()) {
            Output.setText("Errore: nessun dato caricato.");
            return;
        }

        // Chiedi quanti ID eliminare
        String quantiStr = javax.swing.JOptionPane.showInputDialog(this,
                "Quanti elementi vuoi eliminare?");
        if (quantiStr == null) return; // utente ha premuto Annulla

        int quanti;
        try {
            quanti = Integer.parseInt(quantiStr.trim());
            if (quanti <= 0) {
                Output.setText("Errore: inserisci un numero maggiore di zero.");
                return;
            }
        } catch (NumberFormatException e) {
            Output.setText("Errore: inserisci un numero valido.");
            return;
        }

        // Raccogli gli ID uno per uno tramite dialogo
        java.util.ArrayList<String> idsDaEliminare = new java.util.ArrayList<>();
        for (int i = 1; i <= quanti; i++) {
            String idInput = javax.swing.JOptionPane.showInputDialog(this,
                    "Inserisci l'ID " + i + " di " + quanti + " (4 cifre, es. 0001):");
            if (idInput == null) return; // utente ha premuto Annulla
            idInput = idInput.trim();
            if (!idInput.matches("\\d{4}")) {
                Output.setText("Errore: l'ID \"" + idInput + "\" non è valido. Operazione annullata.");
                return;
            }
            if (bs.cercaPerId(idInput).isEmpty()) {
                Output.setText("Errore: nessuna voce trovata con ID " + idInput + ". Operazione annullata.");
                return;
            }
            idsDaEliminare.add(idInput);
        }

        // Blocca il bottone durante l'animazione
        EliminaB.setEnabled(false);
        Output.setText("Eliminazione in corso...");
        ProgressBar.setValue(0);

        // Timer: avanza la progress bar in 5 secondi (100 step da 50ms)
        final int[] step = {0};
        javax.swing.Timer timer = new javax.swing.Timer(50, null);
        timer.addActionListener(e -> {
            step[0]++;
            ProgressBar.setValue(step[0]);

            if (step[0] >= 100) {
                timer.stop();

                // Esegui l'eliminazione reale
                java.util.ArrayList<String> eliminati = new java.util.ArrayList<>();
                java.util.ArrayList<String> nonTrovati = new java.util.ArrayList<>();

                for (String idVoce : idsDaEliminare) {
                    try {
                        bs.eliminaVoce(idVoce);
                        eliminati.add(idVoce);
                    } catch (java.util.NoSuchElementException ex) {
                        nonTrovati.add(idVoce);
                    }
                }

                // Mostra il riepilogo in jTextArea1
                StringBuilder sb = new StringBuilder();
                sb.append("Operazione completata!\n");
                sb.append("=======================================\n");
                sb.append("Voci eliminate (").append(eliminati.size()).append("):\n");
                for (String id : eliminati) {
                    sb.append("  - ID: ").append(id).append("\n");
                }
                if (!nonTrovati.isEmpty()) {
                    sb.append("---------------------------------------\n");
                    sb.append("ID non trovati (").append(nonTrovati.size()).append("):\n");
                    for (String id : nonTrovati) {
                        sb.append("  - ID: ").append(id).append("\n");
                    }
                }
                sb.append("=======================================\n");
                sb.append("Ricorda di salvare il CSV dalla Home.");

                jTextArea1.setText(sb.toString());
                Output.setText("Eliminazione completata: " + eliminati.size() + " voci rimosse.");
                EliminaB.setEnabled(true);
            }
        });
        timer.start();        
    }//GEN-LAST:event_EliminaBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Eliminazione(new BudgetSight()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminaB;
    private javax.swing.JLabel Output;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
