/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import model.BudgetSight;
import model.VoceBudget;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author dario
 */
public class Modifica extends javax.swing.JFrame {
    private BudgetSight bs;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Modifica.class.getName());

    /**
     * Creates new form Modifica
     */
    public Modifica(model.BudgetSight bs) {
        initComponents();
        this.bs = bs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        importo = new javax.swing.JTextField();
        descrizione = new javax.swing.JTextField();
        categoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        budgetAnnuale = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        responsabile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        reparto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ModificaB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(188, 210, 243));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Modifica");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Inserisci l'ID per ricercare l'elemento da modificare");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Descrizione");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Importo");

        descrizione.addActionListener(this::descrizioneActionPerformed);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Categoria");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Data");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Budget Annuale");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Responsabile");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Reparto");

        ModificaB.setBackground(new java.awt.Color(51, 51, 255));
        ModificaB.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ModificaB.setForeground(new java.awt.Color(255, 255, 255));
        ModificaB.setText("Modifica");
        ModificaB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificaBMouseClicked(evt);
            }
        });
        ModificaB.addActionListener(this::ModificaBActionPerformed);

        Output.setColumns(20);
        Output.setRows(5);
        jScrollPane1.setViewportView(Output);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ModificaB))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(reparto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(responsabile, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(budgetAnnuale)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descrizione, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(importo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reparto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responsabile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(budgetAnnuale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descrizione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(ModificaB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificaBActionPerformed

    private void descrizioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descrizioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descrizioneActionPerformed

    private void ModificaBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificaBMouseClicked
                // Controlla che ci siano dati
        if (bs == null || bs.getElenco().isEmpty()) {
            Output.setText("Errore: nessun dato caricato.");
            return;
        }

        // Leggi e valida l'ID
        String idInput = id.getText().trim();
        if (!idInput.matches("\\d{4}")) {
            Output.setText("Errore: l'ID deve essere 4 cifre numeriche (es. 0001).");
            return;
        }

        // Cerca la voce nel modello
        java.util.ArrayList<model.VoceBudget> trovati = bs.cercaPerId(idInput);
        if (trovati.isEmpty()) {
            Output.setText("Nessuna voce trovata con ID: " + idInput);
            return;
        }
        model.VoceBudget vecchia = trovati.get(0);

        // Leggi i campi
        String nomeReparto      = reparto.getText().trim();
        String nomeResponsabile = responsabile.getText().trim();
        String budgetStr        = budgetAnnuale.getText().trim();
        String dataStr          = data.getText().trim();
        String cat              = categoria.getText().trim();
        String desc             = descrizione.getText().trim();
        String importoStr       = importo.getText().trim();

        // Controlla che i campi obbligatori non siano vuoti
        if (nomeReparto.isEmpty() || nomeResponsabile.isEmpty() ||
            budgetStr.isEmpty() || dataStr.isEmpty() ||
            cat.isEmpty() || importoStr.isEmpty()) {
            Output.setText("Errore: compila tutti i campi (Reparto, Responsabile, Budget, Data, Categoria, Importo).");
            return;
        }

        // Parsa i numeri
        double budgetDouble, importoDouble;
        try {
            budgetDouble = Double.parseDouble(budgetStr.replace(",", "."));
        } catch (NumberFormatException e) {
            Output.setText("Errore: Budget Annuale non valido. Inserisci un numero (es. 5000.00).");
            return;
        }
        try {
            importoDouble = Double.parseDouble(importoStr.replace(",", "."));
        } catch (NumberFormatException e) {
            Output.setText("Errore: Importo non valido. Inserisci un numero (es. 250.00).");
            return;
        }

        // Parsa la data
        java.time.LocalDate dataParsed;
        try {
            dataParsed = java.time.LocalDate.parse(dataStr,
                    java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        } catch (java.time.format.DateTimeParseException e) {
            Output.setText("Errore: data non valida. Usa il formato GG-MM-AAAA (es. 15-03-2024).");
            return;
        }

        // Costruisci la voce aggiornata e salva
        try {
            model.VoceBudget aggiornata = new model.VoceBudget(
                idInput, nomeReparto, nomeResponsabile,
                budgetDouble, dataParsed, cat,
                desc.isEmpty() ? null : desc,
                importoDouble
            );
            bs.modificaVoce(aggiornata);

            Output.setText(
                "Modifica effettuata con successo!\n" +
                "---------------------------------------\n" +
                "PRIMA:  " + vecchia.getNomeReparto() + " | " + vecchia.getCategoria() +
                            " | " + vecchia.getDataFormatted() + " | " +
                            String.format("%.2f", vecchia.getImporto()) + " EUR\n" +
                "DOPO:   " + aggiornata.getNomeReparto() + " | " + aggiornata.getCategoria() +
                            " | " + aggiornata.getDataFormatted() + " | " +
                            String.format("%.2f", aggiornata.getImporto()) + " EUR\n" +
                "---------------------------------------\n" +
                "Ricorda di salvare il CSV dalla Home."
            );

        } catch (IllegalArgumentException e) {
            Output.setText("Errore nei dati: " + e.getMessage());
        } catch (java.util.NoSuchElementException e) {
            Output.setText("Errore interno: " + e.getMessage());
        }           // TODO add your handling code here:
    }//GEN-LAST:event_ModificaBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Modifica(new model.BudgetSight()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModificaB;
    private javax.swing.JTextArea Output;
    private javax.swing.JTextField budgetAnnuale;
    private javax.swing.JTextField categoria;
    private javax.swing.JTextField data;
    private javax.swing.JTextField descrizione;
    private javax.swing.JTextField id;
    private javax.swing.JTextField importo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField reparto;
    private javax.swing.JTextField responsabile;
    // End of variables declaration//GEN-END:variables
}
