/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import model.BudgetSight;
import model.VoceBudget;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author dario
 */
public class Ricerca extends javax.swing.JFrame {
    private BudgetSight bs;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ricerca.class.getName());

    /**
     * Creates new form Ricerca
     */
    public Ricerca(BudgetSight bs) {

        initComponents();

        this.bs = bs;

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PannelloRicerca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Selezione = new javax.swing.JComboBox<>();
        Inserimento = new javax.swing.JTextField();
        Cerca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PannelloRicerca.setBackground(new java.awt.Color(188, 210, 243));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Ricerca");

        Selezione.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Reparto", "Data", "Categoria", "Descrizione" }));
        Selezione.addActionListener(this::SelezioneActionPerformed);

        Cerca.setBackground(new java.awt.Color(51, 51, 255));
        Cerca.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Cerca.setForeground(new java.awt.Color(255, 255, 255));
        Cerca.setText("Cerca");
        Cerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CercaMouseClicked(evt);
            }
        });

        OutputArea.setEditable(false);
        OutputArea.setColumns(20);
        OutputArea.setRows(5);
        jScrollPane1.setViewportView(OutputArea);

        javax.swing.GroupLayout PannelloRicercaLayout = new javax.swing.GroupLayout(PannelloRicerca);
        PannelloRicerca.setLayout(PannelloRicercaLayout);
        PannelloRicercaLayout.setHorizontalGroup(
            PannelloRicercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelloRicercaLayout.createSequentialGroup()
                .addGroup(PannelloRicercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PannelloRicercaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(PannelloRicercaLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(Selezione, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Inserimento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Cerca)
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PannelloRicercaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PannelloRicercaLayout.setVerticalGroup(
            PannelloRicercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelloRicercaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(PannelloRicercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Selezione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inserimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cerca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannelloRicerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannelloRicerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelezioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelezioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelezioneActionPerformed

    private void CercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CercaMouseClicked
        if (bs == null || bs.getElenco().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Carica prima un CSV.");
            return;
        }

    String tipo = Selezione.getSelectedItem().toString();

    String valore = Inserimento.getText().trim();

    if (valore.isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Inserisci un valore.");

        return;
    }

ArrayList<VoceBudget> risultati = new ArrayList<>();

    switch (tipo) {

        case "ID":

            risultati = bs.cercaPerId(valore);

            break;

        case "Reparto":

            risultati = bs.cercaPerReparto(valore);

            break;

        case "Data":

            risultati = bs.cercaPerData(valore);

            break;

        case "Categoria":

            risultati = bs.cercaPerCategoria(valore);

            break;

        case "Descrizione":

            risultati = bs.cercaPerDescrizione(valore);

            break;
    }

    OutputArea.setText("");

    if (risultati.isEmpty()) {

        OutputArea.setText("NESSUN RISULTATO TROVATO");

        return;
    }

    String output = "";

    for (VoceBudget v : risultati) {

        output += "ID: " + v.getIdVoce() + "\n";

        output += "Reparto: " + v.getNomeReparto() + "\n";

        output += "Responsabile: " + v.getResponsabile() + "\n";

        output += "Data: " + v.getDataFormatted() + "\n";

        output += "Categoria: " + v.getCategoria() + "\n";

        output += "Descrizione: " + v.getDescrizione() + "\n";

        output += "Importo: € " + v.getImporto() + "\n";

        output += "-----------------------------------\n";
    }

        OutputArea.setText(output);        // TODO add your handling code here:
    }//GEN-LAST:event_CercaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ricerca(new BudgetSight()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerca;
    private javax.swing.JTextField Inserimento;
    private javax.swing.JTextArea OutputArea;
    private javax.swing.JPanel PannelloRicerca;
    private javax.swing.JComboBox<String> Selezione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
