/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import model.*;

/**
 *
 * @author Computer
 */
public class TabellaVoci extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabellaVoci.class.getName());
    private BudgetSight bs;

    //intestazioni dlelle colonne -----> corrispondono ai campi di VoceBudget
    private static final String[] COLONNE = {
        "ID", "Reparto", "Responsabile", "Budget Annuale",
        "Data", "Categoria", "Descrizione", "Importo"
    };
    
    
    /**
     * Creates new form TabellaVoci
     * @param bs Puntatore all'istanza del gestore passata come parametro
     */
    
    public TabellaVoci(BudgetSight bs) {
        this.bs = bs;
        initComponents();
        this.popolaTabella();
        this.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabella = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabella.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabella);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        BudgetSight bs = new BudgetSight();
        java.awt.EventQueue.invokeLater(() -> new TabellaVoci(bs).setVisible(true));
    }
    
    
    /**
     * Legge tutte le VoceBudget dal gestore e le inserisce nel modello della tabella.
     */
    private void popolaTabella() {

        //modello con le intestazioni della tabella
        javax.swing.table.DefaultTableModel modello = new javax.swing.table.DefaultTableModel(COLONNE, 0);

        //recupero l'elenco
        ArrayList<VoceBudget> elenco = bs.getElenco();

        //popolazione del modello
        for (VoceBudget v : elenco) {

            modello.addRow(new Object[]{
                v.getIdVoce(),
                v.getNomeReparto(),
                v.getResponsabile(),
                String.format("€ %,.2f", v.getBudgetAnnuale()),
                v.getDataFormatted(),
                v.getCategoria(),
                v.getDescrizione(),
                String.format("€ %,.2f", v.getImporto())
            });
        }

        //setto il modello alla tabella
        tabella.setModel(modello);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabella;
    // End of variables declaration//GEN-END:variables
}
